# Generated by Django 4.2 on 2023-08-10 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=128, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('category', models.CharField(choices=[('레저/체육/공원', '레저/체육/공원'), ('문화관광/명소', '문화관광/명소'), ('전시/공연', '전시/공연')], max_length=50, null=True)),
                ('parking', models.CharField(choices=[('무료주차', '무료주차'), ('유료주차', '유료주차')], max_length=50, null=True)),
                ('dis_parking', models.CharField(choices=[('장애인 주차구역 있음', '장애인 주차구역 있음'), ('장애인 주차구역 없음', '장애인 주차구역 없음')], max_length=50, null=True)),
                ('big_parking', models.CharField(choices=[('대형차 주차 불가', '대형차 주차 불가'), ('대형차 주차 가능', '대형차 주차 가능')], max_length=50, null=True)),
                ('wheelchair', models.CharField(choices=[('휠체어 대여 불가', '휠체어 대여 불가'), ('휠체어 대여 가능', '휠체어 대여 가능')], max_length=50, null=True)),
                ('toilet', models.CharField(choices=[('장애인 화장실 없음', '장애인 화장실 없음'), ('장애인 화장실 있음', '장애인 화장실 있음')], max_length=50, null=True)),
                ('braille', models.CharField(choices=[('장애인 안내 점자 없음', '장애인 안내 점자 없음'), ('장애인 안내 점자 있음', '장애인 안내 점자 있음')], max_length=50, null=True)),
                ('audio', models.CharField(choices=[('오디오 가이드 없음(한국어)', '오디오 가이드 없음(한국어)'), ('오디오 가이드 있음(한국어)', '오디오 가이드 있음(한국어)')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recomment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomments', to='main.comment')),
                ('relikes', models.ManyToManyField(blank=True, related_name='liked_recomments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('painter', models.CharField(max_length=30, null=True)),
                ('drawing_technique', models.CharField(max_length=50, null=True)),
                ('work_year', models.CharField(max_length=20, null=True)),
                ('content', models.TextField(null=True)),
                ('type', models.CharField(choices=[('고전미술', '고전미술'), ('현대미술', '현대미술')], max_length=128, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('scraps', models.ManyToManyField(blank=True, related_name='scraped_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='main.post'),
        ),
    ]
