# Generated by Django 4.2 on 2023-08-09 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=128)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('레저/체육/공원', '레저/체육/공원'), ('문화관광/명소', '문화관광/명소'), ('전시/공연', '전시/공연')], max_length=50)),
                ('parking', models.CharField(choices=[('무료주차', '무료주차'), ('유료주차', '유료주차'), ('장애인주차', '장애인주차')], max_length=50)),
                ('facilities', models.CharField(choices=[('장애인화장실', '장애인화장실'), ('휠체어대여', '휠체어대여')], max_length=50)),
                ('guide', models.CharField(choices=[('점자가이드', '점자가이드'), ('한국어오디오가이드', '한국어오디오가이드')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recomment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomments', to='main.comment')),
                ('relikes', models.ManyToManyField(blank=True, related_name='liked_recomments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('painter', models.CharField(max_length=30)),
                ('drawing_technique', models.CharField(max_length=50)),
                ('work_year', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('type', models.CharField(choices=[('고전미술', '고전미술'), ('현대미술', '현대미술')], max_length=128)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('scraps', models.ManyToManyField(blank=True, related_name='scraped_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='main.post'),
        ),
    ]
