# Generated by Django 4.2 on 2023-08-04 06:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='scrap',
            field=models.ManyToManyField(related_name='scrap_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
