# Generated by Django 4.2 on 2023-08-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_recomment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='drawing_technique',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='painter',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='work_year',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
