# Generated by Django 4.2 on 2023-08-05 12:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_scrap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='scrap',
        ),
        migrations.AddField(
            model_name='post',
            name='scraps',
            field=models.ManyToManyField(blank=True, related_name='scraped_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
