# Generated by Django 4.2 on 2023-08-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_post_drawing_technique_alter_post_painter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('고전미술', '고전미술'), ('현대미술', '현대미술')], max_length=128, null=True),
        ),
    ]
