# Generated by Django 4.2 on 2023-08-06 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_likes_comment_relikes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='relikes',
            new_name='likes',
        ),
        migrations.RenameField(
            model_name='recomment',
            old_name='likes',
            new_name='relikes',
        ),
    ]
